"use strict";
let x = 7;
x = x % 3;
let y = 21;
y = y % 4;
let z = 13;
z = z % 2;
console.log(`the value of x after the calculation: ${x}`);
console.log(`the value of y after the calculation: ${y}`);
console.log(`the value of z after the calculation: ${z}`);
